
[general]
	#Remove vanilla recipes that are changed by mod or break mod gameplay (wooden tools, torch)
	removeVanillaRecipes = true
	#Remove spawning of vanilla animals like cows, pigs, sheeps
	removeVanillaGeneratedAnimals = true
	#Domesticate wild animal after given generations
	#Range: > 1
	domesticateAfterGenerations = 3
	#Chance of finishing recipe in tanning rack
	#Range: 0.001 ~ 1.0
	tanningRackFinishChance = 0.1
	#Chance of breed effect from feeder every 1/X tick
	#Range: > 1
	feederTickChanceBreedAnimal = 200
	#Feeder area of breed effect
	#Range: 0 ~ 15
	feederEffectRange = 4
	#Force tool for wood material - harvestable only with axe
	forceToolForWood = true
	#Give player manual on first connect to game
	givePlayerManualOnFirstConnect = true
	#Chance of successfull fishing every 1/X tick (randomly)
	#Range: > 1
	fishingNetChance = 3600
	#Disable use of vanilla crafting table until end of Stone Age
	disableVanillaCraftingTable = true
	#List of blocks that have disabled use until end of stone age
	disabledUseInStoneAgeList = ["minecraft:crafting_table"]

[structures]
	#Abandoned camp spawn chance
	#Range: 4.9E-324 ~ 1.0
	abandonedCampSpawnChance = 0.001

["mob spawning"]

	["mob spawning".deer]
		#Enable spawning of mob
		spawnDeerEnable = true
		#Spawn weight of mob
		#Range: 0 ~ 100
		spawnDeerWeight = 20
		#Spawn min count of mob
		#Range: 1 ~ 100
		spawnDeerMinCount = 4
		#Spawn max count of mob
		#Range: 1 ~ 100
		spawnDeerMaxCount = 10

	["mob spawning".boar]
		#Enable spawning of mob
		spawnBoarEnable = true
		#Spawn weight of mob
		#Range: 0 ~ 100
		spawnBoarWeight = 10
		#Spawn min count of mob
		#Range: 1 ~ 100
		spawnBoarMinCount = 4
		#Spawn max count of mob
		#Range: 1 ~ 100
		spawnBoarMaxCount = 6
		#Result of breeding after generations in captivity
		boarBreedingResult = "minecraft:pig"

	["mob spawning".auroch]
		#Enable spawning of mob
		spawnAurochEnable = true
		#Spawn weight of mob
		#Range: 0 ~ 100
		spawnAurochWeight = 10
		#Spawn min count of mob
		#Range: 1 ~ 100
		spawnAurochMinCount = 4
		#Spawn max count of mob
		#Range: 1 ~ 100
		spawnAurochMaxCount = 8
		#Result of breeding after generations in captivity
		aurochBreedingResult = "minecraft:cow"

	["mob spawning".fowl]
		#Enable spawning of mob
		spawnFowlEnable = true
		#Spawn weight of mob
		#Range: 0 ~ 100
		spawnFowlWeight = 10
		#Spawn min count of mob
		#Range: 1 ~ 100
		spawnFowlMinCount = 6
		#Spawn max count of mob
		#Range: 1 ~ 100
		spawnFowlMaxCount = 8
		#Result of breeding after generations in captivity
		fowlBreedingResult = "minecraft:chicken"

	["mob spawning".mouflon]
		#Enable spawning of mob
		spawnMouflonEnable = true
		#Spawn weight of mob
		#Range: 0 ~ 100
		spawnMouflonWeight = 10
		#Spawn min count of mob
		#Range: 1 ~ 100
		spawnMouflonMinCount = 4
		#Spawn max count of mob
		#Range: 1 ~ 100
		spawnMouflonMaxCount = 8
		#Result of breeding after generations in captivity
		mouflonBreedingResult = "minecraft:sheep"

	["mob spawning".mammoth]
		#Enable spawning of mob
		spawnMammothEnable = true
		#Spawn weight of mob
		#Range: 0 ~ 100
		spawnMammothWeight = 10
		#Spawn min count of mob
		#Range: 1 ~ 100
		spawnMammothMinCount = 2
		#Spawn max count of mob
		#Range: 1 ~ 100
		spawnMammothMaxCount = 4

	["mob spawning"."saber tooth tiger"]
		#Enable spawning of mob
		spawnSaberToothTigerEnable = true
		#Spawn weight of mob
		#Range: 0 ~ 100
		spawnSaberToothTigerWeight = 5
		#Spawn min count of mob
		#Range: 1 ~ 100
		spawnSaberToothTigerMinCount = 1
		#Spawn max count of mob
		#Range: 1 ~ 100
		spawnSaberToothTigerMaxCount = 2

	["mob spawning"."woolly rhino"]
		#Enable spawning of mob
		spawnWoollyRhinoEnable = true
		#Spawn weight of mob
		#Range: 0 ~ 100
		spawnWoollyRhinoWeight = 10
		#Spawn min count of mob
		#Range: 1 ~ 100
		spawnWoollyRhinoMinCount = 2
		#Spawn max count of mob
		#Range: 1 ~ 100
		spawnWoollyRhinoMaxCount = 6

	["mob spawning"."terror bird"]
		#Enable spawning of mob
		spawnTerrorBirdEnable = true
		#Spawn weight of mob
		#Range: 0 ~ 100
		spawnTerrorBirdWeight = 5
		#Spawn min count of mob
		#Range: 1 ~ 100
		spawnTerrorBirdMinCount = 1
		#Spawn max count of mob
		#Range: 1 ~ 100
		spawnTerrorBirdMaxCount = 3

	["mob spawning".coelacanth]
		#Enable spawning of mob
		spawnCoelacanthEnable = true
		#Spawn weight of mob
		#Range: 0 ~ 100
		spawnCoelacanthWeight = 5
		#Spawn min count of mob
		#Range: 1 ~ 100
		spawnCoelacanthMinCount = 1
		#Spawn max count of mob
		#Range: 1 ~ 100
		spawnCoelacanthMaxCount = 3

[aqueduct]
	#List of biomes where aqueduct doesn't remove water source
	infinityWaterSourceBiomeList = []

[Config]
	#If grass bed can sleep
	sleep = true
	#If Drying rack need daytime
	needDaytime = true
	makeFire = true
	litTorche = true

